### ISSUE TITLE
Truffle unbox issues

### ISSUE THREAD

**Issue by rjgeek** [oasislabs/oasis-box#11]
If you're using Solidity outside of Contract Kit, ensure you have truffle v5 installed. If you have another version of truffle installed you'll want to either uninstall it or ensure you're using v5 with this box.

```npm uninstall -g truffle```

``npm install -g truffle@5.0.0-beta.1``

Now download the truffle box.

``truffle unbox oasislabs/oasis-box``

-----------------------------------------------------------
## Detail

$ >>:~/new_project/secret-ballot/oasis-box$ truffle unbox oasislabs/oasis-box
/usr/lib/node_modules/truffle/build/cli.bundled.js:41447
  fork: async function(config, callback) {
              ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by armaniferrante** [comment]
Thanks for the report. There's been issues with truffle in beta.1. Does upgrading to beta.2 fix the problem?

`npm install -g truffle@5.0.0-beta.2`

We've updated the readme to use this.

**Comment by rjgeek** [comment]
Thank you for your kindly suggestion, but sorry to say, it still does not work well, I give the whole steps I have made.

## step 1
`` $>> sudo npm uninstall -g truffle``
- ansi-regex@3.0.0 node_modules/truffle/node_modules/ansi-regex
- balanced-match@1.0.0 node_modules/truffle/node_modules/balanced-match
- bindings@1.3.1 node_modules/truffle/node_modules/bindings
- browser-stdout@1.3.0 node_modules/truffle/node_modules/browser-stdout
....
## step 2
``$>> ~/new_project/secret-ballot$ sudo npm install -g truffle@5.0.0-beta.2``
/usr/bin/truffle -> /usr/lib/node_modules/truffle/build/cli.bundled.js

 keccak@1.4.0 install /usr/lib/node_modules/truffle/node_modules/keccak
 npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

keccak@1.4.0 rebuild /usr/lib/node_modules/truffle/node_modules/keccak
 node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/truffle/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakSponge.o
  CC(target) Release/obj.target/keccak/src/libkeccak/KeccakP-1600-reference.o
  SOLINK_MODULE(target) Release/obj.target/keccak.node
  COPY Release/keccak.node
make: Leaving directory '/usr/lib/node_modules/truffle/node_modules/keccak/build'
/usr/lib
└─┬ truffle@5.0.0-beta.2 
  ├─┬ mocha@4.1.0 
  │ ├── browser-stdout@1.3.0 
  │ ├── commander@2.11.0 
  │ ├─┬ debug@3.1.0 
  │ │ └── ms@2.0.0 
  │ ├── diff@3.3.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ glob@7.1.2 
  │ │ ├── fs.realpath@1.0.0 
  │ │ ├─┬ inflight@1.0.6 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ minimatch@3.0.4 
  │ │ │ └─┬ brace-expansion@1.1.11 
  │ │ │   ├── balanced-match@1.0.0 

## step 3
``$>> ~/new_project/secret-ballot$ sudo truffle unbox oasislabs/oasis-box``

/usr/lib/node_modules/truffle/build/cli.bundled.js:61310
  fork: async function(config, callback) {
              ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

**Comment by armaniferrante** [comment]
What version of `node` are you using?

**Comment by rjgeek** [comment]
Thanks, @armaniferrante , the problems are solved after I use node v8.10.0
